/// <reference path="../pb_data/types.d.ts" />

// 99 компаний (ООО, высокая достоверность данных) из базы
// prospects (Perplexity + собственный поиск, сентябрь 2026) — карточки
// добавлены редакцией по открытым данным, без запроса самих компаний, как
// обсуждалось 2026-09-28 (см. STATUS.md). Только юрлица, не физлица/ИП —
// см. комментарий в 1755000060. Каждая карточка на сайте помечена, что
// добавлена редакцией, и ведёт на форму "это моя компания" / "уберите"
// (unclaimed_claims). Откат удаляет ровно эти записи по domain.
const LISTINGS = [
  { name: "Firecode", domain: "firecode.ru", website: "https://firecode.ru", legal_name: "ООО \"ИТ-ГРУПП\"", inn: "6164309078", city: "Ростов-на-Дону", blurb: "Проектирует, запускает и сопровождает ИИ-агентов, включая мультиагентные решения", categories: ["ai-agents", "rag", "ai-analytics", "chatbots"], source_email: "info@firecode.ru", source_phone: "+7 (499) 130-51-77" },
  { name: "Meanotek", domain: "meanotek.io", website: "https://meanotek.io", legal_name: "ООО \"МЕАНОТЕК\"", inn: "1660309848", city: "Казань", blurb: "Делает специализированных ИИ-агентов в контуре заказчика", categories: ["ai-agents"], source_email: "info@meanotek.io", source_phone: "+7 (843) 254-51-54" },
  { name: "Friflex / Flexar", domain: "friflex.com", website: "https://friflex.com", legal_name: "ООО \"ФРИФЛЕКС\"", inn: "7726434385", city: "Г.Москва", blurb: "Внедряет ИИ-агентов для обработки отзывов, документов и корпоративных данных", categories: ["ai-agents", "rag"], source_email: "hello@friflex.com", source_phone: "+7 (495) 885-61-79" },
  { name: "iiautomation", domain: "iiautomation.ru", website: "https://iiautomation.ru", legal_name: "ООО \"ИИ-АВТОМАТИЗАЦИЯ\"", inn: "7720970478", city: "Москва", blurb: "Внедряет AI-агентов, CRM-автоматизации и решения для Bitrix24", categories: ["ai-agents", "crm-ai", "orchestration"], source_email: "cloudcoreteam@yandex.ru", source_phone: "" },
  { name: "Digital-Pro Tech", domain: "digital-pro.tech", website: "https://digital-pro.tech", legal_name: "ООО \"ИТЦ ЦВЕТКОВ\"", inn: "7701392711", city: "Москва", blurb: "Внедряет готовые и кастомные AI-сценарии для продаж, поддержки, HR, финансов", categories: ["ai-agents", "ai-analytics", "crm-ai", "prompt-engineering"], source_email: "hello@digital-pro.tech", source_phone: "+7 (915) 079-35-45" },
  { name: "Lovat AI", domain: "lovatai.ru", website: "https://lovatai.ru", legal_name: "ООО \"МАРКПРИОР\"", inn: "3812047819", city: "Ярославская область", blurb: "Настраивает ИИ-агентов для клиентской поддержки и HR", categories: ["ai-agents"], source_email: "info@lovatai.ru", source_phone: "+7 (985) 003-24-18" },
  { name: "Grinit", domain: "grinit.ru", website: "https://grinit.ru", legal_name: "ООО \"ГРИНИТ\"", inn: "6732180786", city: "Смоленск", blurb: "Собирает и внедряет кастомных ИИ-агентов для документов, заявок, HR", categories: ["ai-agents"], source_email: "project@grinit.ru", source_phone: "+7 (993) 898-44-62" },
  { name: "Rubius", domain: "rubius.com", website: "https://rubius.com", legal_name: "ООО \"РУБИУС ГРУПП\"", inn: "7017252288", city: "Томск", blurb: "Делает ИИ-решения для бизнеса, включая HR-агента", categories: ["ai-agents"], source_email: "info@rubius.com", source_phone: "" },
  { name: "AISender", domain: "aisender.ru", website: "https://aisender.ru", legal_name: "ООО \"АИСЕНДЕР\"", inn: "1644106424", city: "Бугульма (Татарстан)", blurb: "Настраивает AI-агентов в Telegram для общения с клиентами и CRM", categories: ["ai-agents", "crm-ai", "prompt-engineering"], source_email: "aisender.ru@gmail.com", source_phone: "" },
  { name: "NIKTA", domain: "nikta.ai", website: "https://nikta.ai", legal_name: "ООО \"ЗВЕНО\"", inn: "5260491864", city: "Нижний Новгород", blurb: "Внедряет ИИ-агентов для заявок, документов, CRM, 1С, Telegram", categories: ["ai-agents", "rag"], source_email: "info@nikta.ai", source_phone: "+7 (499) 213-00-67" },
  { name: "EORA", domain: "eora.ru", website: "https://eora.ru", legal_name: "ООО \"ЗЕН СОЛЮШНС\"", inn: "7733888439", city: "Ижевск", blurb: "Внедряет AI-агентов для контакт-центров, HR, финансов, корпоративных знаний", categories: ["ai-agents", "chatbots", "rag", "ai-video"], source_email: "hello@eora.ru", source_phone: "+7 (495) 414-40-49" },
  { name: "Andes CRM", domain: "andescrm.ru", website: "https://andescrm.ru", legal_name: "ООО \"АНДЕС ЦРМ\"", inn: "5401401288", city: "Новосибирск", blurb: "Создаёт голосовых AI-агентов и интеграции с CRM, 1С, телефонией", categories: ["ai-agents"], source_email: "info@andescrm.ru", source_phone: "+7 (923) 223-23-69" },
  { name: "Bokiva", domain: "bokiva.ru", website: "https://bokiva.ru", legal_name: "ООО \"ГОРОДА ЛАЙФ\"", inn: "6686129736", city: "Екатеринбург", blurb: "Внедряет AI-агентов с подключением к CRM, ERP, Telegram, Bitrix24, amoCRM", categories: ["ai-agents", "crm-ai", "ai-analytics"], source_email: "info@bokiva.ru", source_phone: "+7 (343) 300-90-28" },
  { name: "Pelid Team", domain: "pelidteam.ru", website: "https://pelidteam.ru", legal_name: "ООО \"ДЕВМАН\"", inn: "5001149108", city: "Балашиха (Московская обл.)", blurb: "Разрабатывает индивидуальных AI-агентов и CRM-решения", categories: ["ai-agents", "chatbots", "crm-ai"], source_email: "info@pelidteam.ru", source_phone: "+7 (926) 368-26-38" },
  { name: "Embedika", domain: "embedika.ru", website: "https://embedika.ru/", legal_name: "ООО \"ЭМБЕДИКА\"", inn: "9705130862", city: "Г.Москва", blurb: "RAG-сценарии для корпоративных данных, баз знаний и FAQ", categories: ["rag", "ai-analytics"], source_email: "info@embedika.ru", source_phone: "+7 (499) 993-21-67" },
  { name: "CleverBots", domain: "cleverbots.ru", website: "https://cleverbots.ru/", legal_name: "ООО \"УМНЫЕ ТЕХНОЛОГИЧЕСКИЕ РЕШЕНИЯ\"", inn: "7743218955", city: "Г.Москва", blurb: "RAG-системы, корпоративные ассистенты и чат-боты", categories: ["rag", "chatbots"], source_email: "info@cleverbots.ru", source_phone: "+7 (495) 115-82-19" },
  { name: "CodeInside / Docora AI", domain: "codeinside.ru", website: "https://codeinside.ru/", legal_name: "ООО \"КОДИНСАЙД\"", inn: "5837040135", city: "Пенза", blurb: "RAG-поиск по техдокументации и корпоративным источникам", categories: ["rag", "ai-agents"], source_email: "request@codeinside.ru", source_phone: "+7 (841) 245-84-19" },
  { name: "Raft", domain: "raft.ru", website: "https://raft.ru/", legal_name: "ООО \"РАФТ\"", inn: "7709882877", city: "Г.Москва", blurb: "Корпоративные базы знаний и поиск документов на LLM/RAG", categories: ["rag"], source_email: "info@raft.ru", source_phone: "+7 (495) 215-10-01" },
  { name: "DUC Technologies", domain: "duc-technologies.ru", website: "https://duc-technologies.ru/", legal_name: "ООО \"ДЮК ТЕХНОЛОГИИ\"", inn: "5027308419", city: "Московская область", blurb: "RAG и GraphRAG, графы знаний, AI-ассистенты", categories: ["rag", "ai-agents", "chatbots", "ai-analytics"], source_email: "sales@duc-technologies.ru", source_phone: "+7 (917) 399-12-12" },
  { name: "Aspirity", domain: "aspirity.ru", website: "https://aspirity.ru/", legal_name: "ООО \"АСПИРИТИ\"", inn: "2463256437", city: "Красноярский край", blurb: "RAG-системы, LLM-решения и AI-анализ переговоров", categories: ["rag", "ai-agents", "ai-analytics", "chatbots"], source_email: "hi@aspirity.com", source_phone: "+7 (391) 205-00-55" },
  { name: "TexSoft", domain: "texsoft.ru", website: "https://texsoft.ru/", legal_name: "ООО \"ТЕХСОФТ\"", inn: "9714074371", city: "Г.Москва", blurb: "Разработка RAG-систем и корпоративных цифровых продуктов", categories: ["rag", "chatbots", "ai-agents"], source_email: "info@texsoft.ru", source_phone: "+7 (495) 825-08-80" },
  { name: "Resolventa Group", domain: "resolventagroup.ru", website: "https://resolventagroup.ru/", legal_name: "ООО \"РЕЗОСОФТ\"", inn: "5406820356", city: "Новосибирск", blurb: "RAG-системы, веб-сервисы и приложения", categories: ["rag"], source_email: "hello@resolventagroup.ru", source_phone: "+7 (923) 111-70-70" },
  { name: "DBI / DataBase Intelligence", domain: "dbi.ru", website: "https://dbi.ru/", legal_name: "ООО \"ДИБИАЙ\"", inn: "6166100603", city: "Ростовская область", blurb: "Корпоративные бизнес-приложения и RAG-боты", categories: ["rag", "orchestration", "ai-analytics"], source_email: "contact@dbi.ru", source_phone: "+7 (800) 777-35-28" },
  { name: "Vocamate AI", domain: "vocamate.ru", website: "https://www.vocamate.ru/", legal_name: "ООО \"ПРОФ ИТ\"", inn: "6165125468", city: "Ростовская область", blurb: "LLM/RAG-боты по продуктовой и корпоративной документации", categories: ["rag", "chatbots", "voice-ai", "ai-agents"], source_email: "info@vocamate.ru", source_phone: "+7 (499) 490-44-61" },
  { name: "Secret Agents", domain: "secret-agents.ru", website: "https://secret-agents.ru", legal_name: "ООО \"СЕКРЕТНЫЕ АГЕНТЫ\"", inn: "5032348512", city: "Московская область", blurb: "", categories: ["orchestration", "chatbots", "ai-agents"], source_email: "sales@secret-agents.ru", source_phone: "+7 (495) 868-08-00" },
  { name: "KT Team", domain: "kt-team.ru", website: "https://kt-team.ru", legal_name: "ООО \"КТ ГРУПП\"", inn: "9710069518", city: "Самарская область", blurb: "", categories: ["orchestration", "rag", "ai-analytics", "ai-agents"], source_email: "corporate@kt-team.ru", source_phone: "+7 (495) 204-14-33" },
  { name: "ИИ-студия АПЕТ", domain: "ai-business-projects.ru", website: "https://ai-business-projects.ru", legal_name: "ООО \"БИЗНЕС-ОРБИТА\"", inn: "9715398964", city: "Г.Москва", blurb: "", categories: ["orchestration", "rag", "chatbots", "prompt-engineering"], source_email: "info@apetr.ru", source_phone: "+7 (916) 611-69-91" },
  { name: "WebDoka", domain: "webdoka.ru", website: "https://webdoka.ru", legal_name: "ООО \"ВЕБДОКА\"", inn: "7802754580", city: "Г.Санкт-Петербург", blurb: "", categories: ["orchestration", "crm-ai"], source_email: "sales@webdoka.ru", source_phone: "+7 (911) 147-11-00" },
  { name: "Bitforspro", domain: "bitforspro.ru", website: "https://bitforspro.ru", legal_name: "ООО \"БИТФОРСПРО\"", inn: "7840122328", city: "Г.Санкт-Петербург", blurb: "", categories: ["orchestration", "crm-ai", "chatbots"], source_email: "info@bitforspro.ru", source_phone: "+7 (495) 182-61-61" },
  { name: "mworks (Чебоксары)", domain: "cheb.mworks.ru", website: "https://cheb.mworks.ru", legal_name: "ООО \"МЕДИА ВОРКС АЙТИ\"", inn: "2100000872", city: "Чувашская Республика - Чувашия", blurb: "", categories: ["orchestration", "crm-ai"], source_email: "top@mworks.ru", source_phone: "+7 (835) 223-71-99" },
  { name: "Любава AI", domain: "lubava.ai", website: "https://lubava.ai", legal_name: "ООО \"ЦЕНТР РАЗРАБОТКИ ИТ-СЕРВИСОВ ДИНГО\"", inn: "5410097764", city: "Новосибирск", blurb: "WhatsApp-боты на базе нейросетей, интеграция с бизнес-системами", categories: ["chatbots", "ai-agents", "crm-ai"], source_email: "info@lubava.ai", source_phone: "+7 (383) 363-06-59" },
  { name: "Metabot", domain: "metabot24.ru", website: "https://metabot24.ru", legal_name: "ООО НПО \"МЕТАРЕКС\"", inn: "2608011560", city: "Ставропольский край", blurb: "Кастомные AI-чат-боты для B2B, CRM и бизнес-систем", categories: ["chatbots", "ai-agents"], source_email: "hi@metabot.org", source_phone: "+7 (906) 468-83-42" },
  { name: "MatrixMSK", domain: "matrixmsk.ru", website: "https://matrixmsk.ru", legal_name: "ООО \"МАТРИЦА\"", inn: "7707377692", city: "Москва", blurb: "AI-боты Telegram/WhatsApp с 1С: каталог, остатки, заявки, статусы заказов и производственный план", categories: ["chatbots", "ai-agents"], source_email: "robot@matrixmsk.ru", source_phone: "+7 (495) 308-33-43" },
  { name: "PapAI Soft", domain: "papaisoft.com", website: "https://papaisoft.com", legal_name: "ООО \"ПАПАИ СОФТ\"", inn: "7810978753", city: "Санкт-Петербург", blurb: "Telegram-боты и AI-ассистенты с CRM-интеграцией, оплатой и хостингом", categories: ["chatbots", "ai-agents"], source_email: "s@ppai.info", source_phone: "+7 (993) 983-09-12" },
  { name: "i-Digital", domain: "i-dgtl.ru", website: "https://i-dgtl.ru", legal_name: "ООО \"АЙДИДЖИТАЛ\"", inn: "7813577816", city: "Санкт-Петербург", blurb: "Чат-боты для Telegram и других мессенджеров; CRM-интеграции, кейсы, запуск под ключ", categories: ["chatbots", "crm-ai"], source_email: "info@i-dgtl.ru", source_phone: "+7 (812) 426-99-88" },
  { name: "Alien Source", domain: "aliensource.org", website: "https://aliensource.org", legal_name: "ООО \"МОДИФИЯ\"", inn: "9728064863", city: "Г.Москва", blurb: "Telegram-боты для онбординга, обучения, HR и поддержки; публичный кейс БМЗ", categories: ["chatbots"], source_email: "hello@aliensource.org", source_phone: "+7 (495) 960-10-04" },
  { name: "Сектор Бизнеса", domain: "agency.sector.business", website: "https://agency.sector.business", legal_name: "ООО \"СЕКТОР БИЗНЕСА ГРУПП\"", inn: "2308262884", city: "Краснодар", blurb: "Чат-боты для бизнеса, CRM-интеграции и поддержка", categories: ["chatbots", "crm-ai"], source_email: "help@sector.business", source_phone: "+7 (965) 266-61-61" },
  { name: "NANO-SOFT", domain: "nanosoft.group", website: "https://nanosoft.group", legal_name: "ООО \"НАНО СОФТ\"", inn: "3500005965", city: "Вологда", blurb: "Telegram-боты для бизнеса: внедрение и доступ пользователей", categories: ["chatbots", "crm-ai"], source_email: "nanosoft-1c@yandex.ru", source_phone: "+7 (812) 407-17-67" },
  { name: "Маркетика", domain: "marketica.pro", website: "https://marketica.pro", legal_name: "ООО \"ВЕБСЕЛЛЕРС\"", inn: "5406738292", city: "Новосибирск", blurb: "Многофункциональные чат-боты с CRM-интеграцией; публичные Telegram-кейсы", categories: ["chatbots", "crm-ai"], source_email: "welcome@marketica.pro", source_phone: "+7 (383) 207-54-06" },
  { name: "ChatLabs", domain: "chatlabs.ru", website: "https://chatlabs.ru", legal_name: "ООО \"ИТ ЛАБОРАТОРИЯ\"", inn: "6700031478", city: "Смоленская область", blurb: "", categories: ["chatbots", "ai-agents"], source_email: "hi@chatlabs.ru", source_phone: "+7 (931) 106-80-00" },
  { name: "MediaTen", domain: "mediaten.ru", website: "https://mediaten.ru", legal_name: "ООО \"МЕДИАТЕН\"", inn: "6684035264", city: "Свердловская область", blurb: "", categories: ["chatbots"], source_email: "admin@mediaten.ru", source_phone: "+7 (902) 271-85-91" },
  { name: "CraftTalk", domain: "crafttalk.ru", website: "https://crafttalk.ru", legal_name: "ООО \"КРАФТ-ТОЛК\"", inn: "7728371814", city: "Г.Москва", blurb: "", categories: ["chatbots"], source_email: "info@crafttalk.ru", source_phone: "+7 (499) 651-42-00" },
  { name: "Voxys", domain: "voxys.ru", website: "https://voxys.ru", legal_name: "ООО \"ВОКСИС\"", inn: "6674223607", city: "Свердловская область", blurb: "", categories: ["chatbots", "voice-ai", "crm-ai"], source_email: "sales@voxys.ru", source_phone: "+7 (800) 707-10-00" },
  { name: "BotCreators", domain: "botcreators.ru", website: "https://botcreators.ru", legal_name: "ООО \"ИСА\"", inn: "7725497079", city: "Г.Москва", blurb: "", categories: ["chatbots"], source_email: "info@botcreators.ru", source_phone: "+7 (800) 550-47-15" },
  { name: "Online Media", domain: "online-media.ru", website: "https://online-media.ru", legal_name: "ООО \"АДЕКС\"", inn: "7017081674", city: "Томская область", blurb: "", categories: ["chatbots"], source_email: "ok@online-media.ru", source_phone: "+7 (800) 201-99-21" },
  { name: "CMDF5", domain: "cmdf5.ru", website: "https://cmdf5.ru", legal_name: "ООО \"КОМАНДА Ф5\"", inn: "2130183567", city: "Чувашская Республика - Чувашия", blurb: "", categories: ["crm-ai"], source_email: "info@comf5.ru", source_phone: "+7 (495) 181-08-05" },
  { name: "Neuro.net", domain: "neuro.net", website: "https://neuro.net", legal_name: "ООО \"НЕЙРОСЕТЬ\"", inn: "9703142340", city: "Москва", blurb: "Voice AI: входящие/исходящие звонки, LLM-агенты, квалификация, запись в CRM, контакт-центр", categories: ["voice-ai", "chatbots", "ai-video", "ai-agents"], source_email: "info@neuro.net", source_phone: "+7 (800) 700-78-75" },
  { name: "Zvonobot", domain: "zvonobot.ru", website: "https://zvonobot.ru", legal_name: "ООО \"ВИДЖЕТ\"", inn: "5902016512", city: "Москва", blurb: "Голосовой AI-робот: входящие/исходящие, квалификация лидов, CRM, запись, обзвон и автоинформирование", categories: ["voice-ai"], source_email: "info@zvonobot.ru", source_phone: "+7 (800) 775-34-60" },
  { name: "RoboVoice", domain: "robo-voice.ru", website: "https://robo-voice.ru", legal_name: "ООО \"РОБОВОЙС\"", inn: "9715347247", city: "Москва", blurb: "Голосовые и текстовые роботы для входящих обращений, контакт-центра и омниканальной поддержки", categories: ["voice-ai", "chatbots", "crm-ai", "orchestration"], source_email: "info@slsoft.ru", source_phone: "+7 (499) 460-41-26" },
  { name: "Fromtech", domain: "fromtech.ru", website: "https://fromtech.ru", legal_name: "ООО \"ФРОМТЕК\"", inn: "5024198630", city: "Красногорск, Московская область", blurb: "Голосовые роботы и AI-агенты для входящей линии, CRM, идентификации и мультисценарной поддержки", categories: ["voice-ai", "ai-agents"], source_email: "info@fromtech.ru", source_phone: "+7 (499) 649-77-00" },
  { name: "SmartDialogs", domain: "smartdialogs.net", website: "https://smartdialogs.net", legal_name: "ООО \"СМАРТДИАЛОГС\"", inn: "3665821475", city: "Воронеж", blurb: "Голосовые AI-агенты для входящих и исходящих звонков, SIP-телефония, голос, правила и no-code запуск", categories: ["voice-ai", "ai-agents"], source_email: "sales@smartdialogs.net", source_phone: "+7 (473) 205-90-90" },
  { name: "Скорозвон", domain: "skorozvon.ru", website: "https://skorozvon.ru", legal_name: "ООО \"СМАРТЬЮБ\"", inn: "6658407780", city: "Екатеринбург", blurb: "Голосовой робот для входящих/исходящих звонков, автоматический дозвон, CRM-интеграции и AI-тренер", categories: ["voice-ai", "crm-ai"], source_email: "welcome@skorozvon.ru", source_phone: "+7 (800) 333-97-02" },
  { name: "АТС / Авиационные технологии связи", domain: "atsaero.ru", website: "https://atsaero.ru", legal_name: "ООО \"АТС\"", inn: "7704856552", city: "Москва", blurb: "ПО «Виртуальный оператор»: голосовые роботы для входящих/исходящих, МФЦ, ЖКХ, контакт-центров и CRM", categories: ["voice-ai", "orchestration"], source_email: "info@atsaero.ru", source_phone: "+7 (800) 302-44-91" },
  { name: "iiLab", domain: "iilab.ai", website: "https://iilab.ai", legal_name: "ООО \"ИИЛАБ\"", inn: "9701314957", city: "Москва", blurb: "Голосовой ИИ-робот: поддержка, продажи, клиентские коммуникации и AI-автоматизация", categories: ["voice-ai"], source_email: "info@iilab.ai", source_phone: "+7 (925) 368-43-22" },
  { name: "Voice Robotics", domain: "voice-robotics.ru", website: "https://voice-robotics.ru", legal_name: "ООО \"ГОЛОСОВЫЕРОБОТЫ\"", inn: "0274914285", city: "Уфа", blurb: "Голосовые роботы для ЖКХ, диспетчеризации, входящих/исходящих коммуникаций и интеграций", categories: ["voice-ai", "chatbots"], source_email: "info@voice-robotics.ru", source_phone: "+7 (927) 081-54-95" },
  { name: "VEYRA", domain: "myveyra.ai", website: "https://myveyra.ai", legal_name: "ООО \"ПЯТЫЙ ЭЛЕМЕНТ\"", inn: "9703222035", city: "Москва", blurb: "Voice AI: диагностика процесса, голосовой агент, CRM, телефония, запуск и сопровождение", categories: ["voice-ai", "ai-agents"], source_email: "team@myveyra.ai", source_phone: "+7 (499) 677-61-14" },
  { name: "VoiceLogic", domain: "voicelogic.ru", website: "https://voicelogic.ru", legal_name: "ООО \"ИНТЕГРАТОР ИИ\"", inn: "9111032491", city: "Крым", blurb: "Voice AI Agent: входящие/исходящие, запись, напоминания, обзвон, квалификация и routing", categories: ["voice-ai", "crm-ai", "chatbots", "ai-agents"], source_email: "info@voicelogic.ru", source_phone: "+7 (978) 852-42-09" },
  { name: "TeMa Ai", domain: "temaai.ru", website: "https://temaai.ru", legal_name: "ООО \"ТЕМА\"", inn: "2404022405", city: "Красноярский край", blurb: "", categories: ["voice-ai", "ai-agents", "crm-ai"], source_email: "001@9897777.ru", source_phone: "+7 (391) 989-77-77" },
  { name: "TSEH Studio", domain: "tseh.studio", website: "https://tseh.studio", legal_name: "ООО \"ЦЕХ\"", inn: "7714430347", city: "Москва", blurb: "Генеративное AI-видео, web и iOS-продукты; создание рекламных и обучающих роликов", categories: ["ai-video"], source_email: "info@tseh.studio", source_phone: "+7 (985) 774-25-54" },
  { name: "Mediabanda", domain: "mediabanda.ru", website: "https://mediabanda.ru", legal_name: "ООО \"КЕЛЕВРО\"", inn: "6162069399", city: "Ростов-на-Дону", blurb: "AI-аватары, цифровые двойники, нейровидео, реклама, обучение, 2D/3D-анимация; контент-подписка для Reels/Shorts/Клипов", categories: ["ai-video"], source_email: "info@mediabanda.ru", source_phone: "+7 (800) 700-05-71" },
  { name: "Связи Agency", domain: "svyazi-agency.ru", website: "https://svyazi-agency.ru", legal_name: "ООО \"СВЯЗИ РЕШАЮТ ВСЁ\"", inn: "9703070209", city: "Москва", blurb: "AI-видео под ключ: Midjourney, SDXL, Firefly, Runway, Pika, D-ID, ElevenLabs; реклама, анимация, аватары, озвучка", categories: ["ai-video", "prompt-engineering"], source_email: "i.zmienko@svyazi-agency.com", source_phone: "+7 (495) 198-91-89" },
  { name: "Видеоника", domain: "videonika.ru", website: "https://videonika.ru", legal_name: "ООО \"ВИДЕОНИКА\"", inn: "5040115550", city: "Москва", blurb: "AI-ролики: сценарий, раскадровка, генерация видео/звука, монтаж и продуктовые видео", categories: ["ai-video", "chatbots"], source_email: "nika@videonika.pro", source_phone: "+7 (903) 960-71-29" },
  { name: "Облако Продакшн", domain: "oblako.video", website: "https://oblako.video", legal_name: "ООО \"ОБЛАКО ПРОДАКШН\"", inn: "3257042985", city: "Брянск", blurb: "Видео, motion-дизайн, нейровидео и AI-инструменты как часть видеопроизводства", categories: ["ai-video"], source_email: "info@oblako.video", source_phone: "+7 (499) 288-88-75" },
  { name: "Допустим Зерно", domain: "dopustimzerno.ru", website: "https://dopustimzerno.ru", legal_name: "ООО \"ХАНТЕРМОБ\"", inn: "7447301466", city: "Челябинская область", blurb: "", categories: ["ai-video"], source_email: "production@huntermob.ru", source_phone: "+7 (909) 071-66-66" },
  { name: "Neurolibs", domain: "neurolibs.ru", website: "https://neurolibs.ru", legal_name: "ООО \"НЕДИДЖИТАЛ 3.0\"", inn: "5041215406", city: "Московская область", blurb: "", categories: ["ai-video", "ai-agents"], source_email: "a@nedigital.ru", source_phone: "+7 (925) 865-08-11" },
  { name: "NextBot", domain: "nextbot.ru", website: "https://nextbot.ru", legal_name: "ООО \"ИИ ПЛАТФОРМА\"", inn: "1800010338", city: "Ижевск", blurb: "AI для Bitrix24 и amoCRM: обработка обращений, лиды/сделки, заполнение полей, воронки, база знаний и мессенджеры", categories: ["crm-ai", "ai-agents"], source_email: "info@nextbot.ru", source_phone: "+7 (778) 896-19-16" },
  { name: "Flysk", domain: "flysk.ru", website: "https://flysk.ru", legal_name: "ООО \"ФЛАЙСК\"", inn: "5032391973", city: "Москва", blurb: "AI для amoCRM: транскрибация звонков/встреч, резюме, распределение по спикерам и автоматизация карточек сделок", categories: ["crm-ai"], source_email: "info@flysk.ru", source_phone: "+7 (495) 733-99-81" },
  { name: "Botseller", domain: "botseller.ru", website: "https://botseller.ru", legal_name: "ООО \"БОТСЕЛЛЕР\"", inn: "9727070663", city: "Иваново", blurb: "AI-сотрудники для входящих, записи, CRM, дожимов, продаж и поиска тёплых лидов", categories: ["crm-ai"], source_email: "info@botseller.ru", source_phone: "+7 (968) 794-06-12" },
  { name: "MakeBiz", domain: "makebiz.life", website: "https://makebiz.life", legal_name: "ООО \"МЕЙК БИЗ\"", inn: "9727005664", city: "Москва", blurb: "Внедрение Bitrix24, AI-агентов, AI-продаж, речевой аналитики, CRM и BI; интеграции с учётными процессами", categories: ["crm-ai", "ai-agents", "ai-analytics"], source_email: "info@makebiz.life", source_phone: "+7 (939) 555-82-15" },
  { name: "FMF.dev", domain: "fmf.dev", website: "https://fmf.dev", legal_name: "ООО \"ЦИТ \"ФМФ\"", inn: "6312123545", city: "Самарская область", blurb: "Внедрение AI в 1С, ERP и CRM: корпоративные AI-системы, аналитика и полный цикл от аудита до поддержки", categories: ["crm-ai", "ai-agents", "ai-analytics", "chatbots"], source_email: "info@fmf.dev", source_phone: "+7 (800) 333-11-26" },
  { name: "Первый Бит", domain: "1cbit.ru", website: "https://1cbit.ru", legal_name: "ООО \"ПЕРВЫЙ БИТ\"", inn: "7728361580", city: "Россия, филиалы", blurb: "ИИ в 1С:CRM, голосовые роботы, чат-боты, продажи и интеграции учётных систем", categories: ["crm-ai", "ai-analytics", "ai-agents"], source_email: "info@1cbit.ru", source_phone: "+7 (495) 748-44-48" },
  { name: "IT-Solution", domain: "it-solution.ru", website: "https://it-solution.ru", legal_name: "ООО \"АЙТИ-ПРОДАКШН\"", inn: "7802638464", city: "Г.Санкт-Петербург", blurb: "", categories: ["crm-ai"], source_email: "info@it-solution.ru", source_phone: "+7 (812) 332-84-32" },
  { name: "Bewise", domain: "bewise.ai", website: "https://bewise.ai", legal_name: "ООО \"БИВАЙЗ ЭЙАЙ\"", inn: "9705210476", city: "Г.Москва", blurb: "", categories: ["crm-ai", "ai-analytics", "ai-agents", "prompt-engineering"], source_email: "sale@bewise.ai", source_phone: "+7 (499) 647-77-31" },
  { name: "A9-Studio", domain: "a9-studio.ru", website: "https://a9-studio.ru", legal_name: "ООО \"ВИ СИ ДЖИ\"", inn: "5263146859", city: "Нижегородская область", blurb: "", categories: ["crm-ai"], source_email: "info@a9-studio.ru", source_phone: "+7 (800) 775-84-07" },
  { name: "RDN Group", domain: "rdn-grp.ru", website: "https://rdn-grp.ru", legal_name: "ООО \"РДН\"", inn: "7709999145", city: "Г.Москва", blurb: "", categories: ["crm-ai"], source_email: "info@rdn-grp.ru", source_phone: "+7 (499) 521-67-20" },
  { name: "LighTech", domain: "thelightech.ru", website: "https://thelightech.ru", legal_name: "ООО \"ЛАЙТЕХ\"", inn: "6161096181", city: "Краснодар", blurb: "Промпт-инжиниринг под ключ: аудит, разработка/оптимизация промптов, шаблоны, интеграция с чат-ботами, CRM и ERP", categories: ["prompt-engineering", "rag", "ai-agents"], source_email: "info@m.thelightech.com", source_phone: "+7 (988) 537-92-99" },
  { name: "Fortech", domain: "fortech.dev", website: "https://fortech.dev", legal_name: "ООО \"ФОРТЕХ\"", inn: "6154162274", city: "Ростов-на-Дону", blurb: "Дообучение LLM: GPT, Llama, Mistral, GigaChat; LoRA, SFT, RLHF; внедрение и поддержка AI в бизнесе", categories: ["prompt-engineering", "ai-agents", "chatbots"], source_email: "partners@fortech.dev", source_phone: "+7 (989) 617-13-94" },
  { name: "Reymer Digital", domain: "reymer.digital", website: "https://reymer.digital", legal_name: "ООО \"РЕЙМЕР ДИДЖИТАЛ\"", inn: "9710102525", city: "Москва", blurb: "Промпт-инжиниринг, файнтюнинг на корпоративных данных, база знаний и интеграция с корпоративными системами", categories: ["prompt-engineering", "ai-agents"], source_email: "info@reymer.digital", source_phone: "+7 (495) 134-29-91" },
  { name: "Intelion Cloud", domain: "intelion.cloud", website: "https://intelion.cloud", legal_name: "ООО \"ИНТЕЛИОН ОБЛАКО\"", inn: "9703176519", city: "Москва", blurb: "GPU-инфраструктура и LoRA/QLoRA-файнтюнинг LLM для моделей Qwen, Llama, Mistral; помощь с развёртыванием", categories: ["prompt-engineering", "ai-analytics", "ai-agents"], source_email: "info@intelion.cloud", source_phone: "+7 (993) 966-59-00" },
  { name: "Z-union", domain: "z-union.ru", website: "https://z-union.ru", legal_name: "ООО \"РЕАЛ-В\"", inn: "2130004426", city: "Москва", blurb: "Заказная разработка AI: LLM/LVM, prompt engineering, fine-tuning LLM/LVM/генеративных моделей, агентные системы", categories: ["prompt-engineering"], source_email: "lab@z-union.ru", source_phone: "+7 (919) 729-86-39" },
  { name: "NLab Team", domain: "nlabteam.com", website: "https://nlabteam.com", legal_name: "ООО \"ИНТЕЛЛЕКТУАЛЬНАЯ РАЗРАБОТКА\"", inn: "7839087125", city: "Санкт-Петербург", blurb: "Prompt engineering, RAG и fine-tuning для текстовых/речевых данных, корпоративных LLM и NLP-задач", categories: ["prompt-engineering"], source_email: "hello@nlabteam.com", source_phone: "+7 (812) 507-68-77" },
  { name: "Tenzor Cloud", domain: "tenzor.cloud", website: "https://tenzor.cloud", legal_name: "ООО \"НАРАЯНА ТРЕЙДИНГ\"", inn: "6452146736", city: "Москва", blurb: "GPU-серверы H100/H200, обучение и fine-tuning LLM до 70B+, инфраструктура для распределённых прогонов", categories: ["prompt-engineering"], source_email: "sales@tenzor.cloud", source_phone: "+7 (499) 281-60-04" },
  { name: "Product Lab", domain: "productlab.ru", website: "https://productlab.ru", legal_name: "ООО \"ПРОДАКТ-ЛАБ\"", inn: "9729408718", city: "Москва", blurb: "Prompt engineering, корпоративные программы и AI-практики для продуктовых команд; кейсы и тренинги", categories: ["prompt-engineering", "ai-analytics", "ai-agents"], source_email: "info@productlab.ru", source_phone: "+7 (495) 133-32-60" },
  { name: "Arcsinus", domain: "arcsinus.ru", website: "https://arcsinus.ru", legal_name: "ООО \"АРКСИНУС\"", inn: "7714894934", city: "Москва", blurb: "LLM, RAG, AI-ассистенты, prompt-настройка и архитектура решений; объясняет выбор между RAG и fine-tuning", categories: ["prompt-engineering"], source_email: "welcome@arcsinus.ru", source_phone: "+7 (495) 279-90-47" },
  { name: "Shtab AI", domain: "shtab.app", website: "https://shtab.app", legal_name: "ООО \"СТИК ПРО\"", inn: "7839130405", city: "Россия", blurb: "Консультации и внедрение AI: промпты, LLM, автоматизация и практические материалы по fine-tuning", categories: ["prompt-engineering", "ai-agents", "ai-analytics", "ai-video"], source_email: "hi@shtab.app", source_phone: "+7 (495) 487-74-44" },
  { name: "Data Light", domain: "data-light.ru", website: "https://data-light.ru", legal_name: "ООО \"ДАТА ЛАЙТ\"", inn: "9714047836", city: "Г.Москва", blurb: "", categories: ["prompt-engineering", "ai-analytics"], source_email: "info@data-light.ru", source_phone: "+7 (921) 924-67-73" },
  { name: "SERAKOV.AI", domain: "serakov.ai", website: "https://serakov.ai", legal_name: "ООО \"СЕРАКОВ.АИ\"", inn: "9721235439", city: "Г.Москва", blurb: "", categories: ["prompt-engineering", "rag"], source_email: "hello@serakov.ai", source_phone: "+7 (910) 299-14-70" },
  { name: "NeuroCore AI", domain: "neuro-core.ru", website: "https://neuro-core.ru", legal_name: "ООО \"ЧЕК-СТАР\"", inn: "5074056864", city: "Московская область", blurb: "", categories: ["prompt-engineering", "ai-agents", "rag", "chatbots"], source_email: "info@neuro-core.ru", source_phone: "+7 (495) 764-34-19" },
  { name: "AIHub", domain: "aihub.ru", website: "https://aihub.ru", legal_name: "ООО \"АИХАБ\"", inn: "9706048191", city: "Москва", blurb: "AI-аналитика звонков: контроль качества, оценка менеджеров, поиск потерь, речевая аналитика и CRM-интеграции", categories: ["ai-analytics", "ai-agents"], source_email: "info@aihub.ru", source_phone: "+7 (901) 634-68-82" },
  { name: "Альфа-КМ", domain: "alpha-km.ru", website: "https://alpha-km.ru", legal_name: "ООО \"АЛЬФА-КМ\"", inn: "6200024419", city: "Рязань", blurb: "ИИ-аналитика звонков, IP-телефония, разработка ПО, 1С-интеграции и отчётность", categories: ["ai-analytics"], source_email: "info@alpha-km.ru", source_phone: "+7 (930) 888-79-99" },
  { name: "КОД9", domain: "code9.studio", website: "https://code9.studio", legal_name: "ООО \"КОД9\"", inn: "5050163338", city: "Московская область", blurb: "AI-аналитик, подготовка данных, ML-модели, прогнозы, интеграции с корпоративными системами и отчётность", categories: ["ai-analytics", "ai-agents", "chatbots"], source_email: "hello@code9.studio", source_phone: "+7 (800) 533-89-88" },
  { name: "Up-im", domain: "up-im.ru", website: "https://up-im.ru", legal_name: "ООО \"МАКСИМУМ-МК\"", inn: "7802549133", city: "Санкт-Петербург", blurb: "AI-отчётность: Метрика + CRM + реклама → аналитическая сводка на естественном языке; маркетинговая автоматизация", categories: ["ai-analytics", "chatbots"], source_email: "info@up-im.ru", source_phone: "+7 (812) 997-77-05" },
  { name: "Andata", domain: "andata.ru", website: "https://andata.ru", legal_name: "ООО \"АНДАТА\"", inn: "7724653712", city: "Москва, Сколково", blurb: "Данные, сегменты, AI-аналитика, персонализация, прогнозирование и автоматические маркетинговые действия", categories: ["ai-analytics", "ai-agents", "rag"], source_email: "info@andata.ru", source_phone: "+7 (800) 505-17-58" },
  { name: "Skyeer", domain: "skyeermap.com", website: "https://skyeermap.com", legal_name: "ООО \"СКАЙЕР ИТ\"", inn: "7714762021", city: "Москва", blurb: "AI-аналитика стройки и геоданных: мониторинг объектов, 2D/3D-измерения, отчёты и прогнозы рисков", categories: ["ai-analytics"], source_email: "info@skyeermap.com", source_phone: "+7 (495) 640-97-62" },
  { name: "BND", domain: "bnd.team", website: "https://bnd.team", legal_name: "ООО \"БНД\"", inn: "7719575346", city: "Москва", blurb: "Предиктивная аналитика: прогноз спроса, рисков, мошенничества, производства и клиентского поведения; ML-модели и внедрение", categories: ["ai-analytics"], source_email: "info@bnd.team", source_phone: "+7 (495) 951-64-56" },
  { name: "Флексайтс", domain: "flexites.org", website: "https://flexites.org", legal_name: "ООО \"ФЛЕКСАЙТС\"", inn: "7447123326", city: "Челябинская область", blurb: "", categories: ["ai-analytics", "ai-agents", "chatbots"], source_email: "info@flexites.org", source_phone: "+7 (351) 267-29-94" },
  { name: "Мэйк", domain: "makeagency.ru", website: "https://makeagency.ru", legal_name: "ООО \"МЭЙК\"", inn: "4205248754", city: "Кемеровская область", blurb: "", categories: ["ai-analytics", "crm-ai"], source_email: "hello@makeagency.ru", source_phone: "+7 (495) 108-24-49" },
  { name: "YuSMP Group", domain: "yusmpgroup.ru", website: "https://yusmpgroup.ru", legal_name: "ООО \"ЮСМП ГРУПП ТЕХНОЛОГИИ\"", inn: "5405070453", city: "Новосибирская область", blurb: "", categories: ["ai-analytics", "ai-agents"], source_email: "sales@yusmpgroup.com", source_phone: "+7 (800) 511-32-27" },
  { name: "Денвик Аналитика", domain: "denvic.tech", website: "https://denvic.tech", legal_name: "ООО \"ДЕНВИК АНАЛИТИКА\"", inn: "1101178666", city: "Республика Коми", blurb: "", categories: ["ai-analytics"], source_email: "partners@denvic.ru", source_phone: "+7 (495) 198-97-07" },
]

migrate((app) => {
  const collection = app.findCollectionByNameOrId("unclaimed_specialists")
  for (const item of LISTINGS) {
    let exists = true
    try {
      app.findFirstRecordByData("unclaimed_specialists", "domain", item.domain)
    } catch (err) {
      exists = false
    }
    if (exists) continue
    const record = new Record(collection)
    for (const key in item) record.set(key, item[key])
    record.set("status", "active")
    app.save(record)
  }
}, (app) => {
  for (const item of LISTINGS) {
    try {
      app.delete(app.findFirstRecordByData("unclaimed_specialists", "domain", item.domain))
    } catch (err) {
      // уже удалена
    }
  }
})
